const CONFIG = {
  repo: 'barrack3030-wq/A-new-Wonderland',
  branch: 'main',
  author: 'aji',
  image: '/images/Poganda-Beach-Banggai-IndonesiaJuara-Trip.webp',
  model: 'gpt-5.6-luna'
};

function doGet() {
  return json_({ ok: true, service: 'Banggai Wonderland CMS', status: 'online' });
}

function doPost(e) {
  try {
    const body = JSON.parse((e && e.postData && e.postData.contents) || '{}');
    const props = PropertiesService.getScriptProperties();
    const accessKey = props.getProperty('CMS_ACCESS_KEY');
    if (!accessKey || body.accessKey !== accessKey) return json_({ ok:false, error:'Unauthorized' });

    if (body.action === 'generate') return generate_(String(body.topic || '').trim());
    if (body.action === 'publish') return publish_(body.articles || {});
    return json_({ ok:false, error:'Unknown action' });
  } catch (err) {
    return json_({ ok:false, error: String(err && err.message ? err.message : err) });
  }
}

function generate_(topic) {
  if (!topic) throw new Error('Topic is required');
  const props = PropertiesService.getScriptProperties();
  const apiKey = props.getProperty('OPENAI_API_KEY');
  if (!apiKey) throw new Error('OPENAI_API_KEY is not configured in Apps Script properties.');

  const prompt = `You are the editorial AI for Banggai Wonderland, a premium tourism website about Luwuk, Banggai Regency, Banggai Islands and Banggai Laut, Indonesia.

User command/topic:
${topic}

Create one SEO-friendly travel article concept in FIVE languages: Indonesian (id), English (en), Spanish (es), French (fr), Chinese Simplified (zh).
The five versions must cover the same factual topic and should read naturally for international travelers. Do not invent exact prices, opening hours, permits, statistics, transport schedules, hotel availability or other precise facts. If a fact is uncertain, write generally.
Use the same featured image for every language: ${CONFIG.image}
Author: ${CONFIG.author}
Date: ${Utilities.formatDate(new Date(), 'Asia/Makassar', 'yyyy-MM-dd')}

Return ONLY valid JSON with this exact structure:
{
  "id": {"title":"...","description":"...","seoTitle":"...","seoDescription":"...","image":"...","imageAlt":"...","author":"aji","pubDate":"YYYY-MM-DD","tags":["..."],"slug":"...","body":"markdown body...","preview":"short preview..."},
  "en": {...},
  "es": {...},
  "fr": {...},
  "zh": {...}
}

Rules:
- slug must be lowercase ASCII with hyphens only and identical across all languages.
- title and description should be concise and SEO-friendly.
- body should be a useful travel article with Markdown headings, practical context and a natural call to action for Banggai Wonderland.
- Do not use HTML.
- Do not put YAML frontmatter inside body.
- Keep the body around 700-1000 words per language.
- Keep the shared image path exactly as provided.`;

  const response = UrlFetchApp.fetch('https://api.openai.com/v1/responses', {
    method: 'post',
    contentType: 'application/json',
    headers: { Authorization: 'Bearer ' + apiKey },
    payload: JSON.stringify({
      model: CONFIG.model,
      input: prompt,
      max_output_tokens: 12000
    }),
    muteHttpExceptions: true
  });

  const code = response.getResponseCode();
  const raw = response.getContentText();
  if (code < 200 || code >= 300) throw new Error('OpenAI API error: ' + raw.slice(0, 1000));

  const data = JSON.parse(raw);
  const text = extractOutputText_(data);
  const clean = text.replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/\s*```$/i, '').trim();
  const articles = JSON.parse(clean);

  ['id','en','es','fr','zh'].forEach(lang => {
    if (!articles[lang]) throw new Error('Missing language: ' + lang);
    articles[lang].image = CONFIG.image;
    articles[lang].author = CONFIG.author;
  });

  return json_({ ok:true, articles:articles });
}

function publish_(articles) {
  const props = PropertiesService.getScriptProperties();
  const githubToken = props.getProperty('GITHUB_TOKEN');
  if (!githubToken) throw new Error('GITHUB_TOKEN is not configured in Apps Script properties.');

  const langs = ['id','en','es','fr','zh'];
  const results = [];
  const slug = String((articles.en && articles.en.slug) || (articles.id && articles.id.slug) || '').trim();
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) throw new Error('Invalid slug generated by AI.');

  langs.forEach(lang => {
    const a = articles[lang];
    if (!a || !a.title || !a.body) throw new Error('Incomplete article for ' + lang);
    const content = frontmatter_(a) + '\n' + a.body.trim() + '\n';
    const path = 'src/content/blog/' + lang + '/' + slug + '.md';
    const existing = githubGet_(path, githubToken);
    const payload = {
      message: 'content: publish AI article ' + lang + ' ' + slug,
      content: Utilities.base64Encode(Utilities.newBlob(content).getBytes()),
      branch: CONFIG.branch
    };
    if (existing && existing.sha) payload.sha = existing.sha;
    const saved = githubPut_(path, payload, githubToken);
    results.push({ lang:lang, path:path, commit:saved.commit && saved.commit.sha ? saved.commit.sha : '' });
  });

  return json_({ ok:true, message:'Published 5 language versions to GitHub. Vercel should deploy automatically.', results:results });
}

function frontmatter_(a) {
  const lines = [
    '---',
    'title: ' + yaml_(a.title),
    'description: ' + yaml_(a.description),
    'seoTitle: ' + yaml_(a.seoTitle || a.title),
    'seoDescription: ' + yaml_(a.seoDescription || a.description),
    'image: ' + yaml_(CONFIG.image),
    'imageAlt: ' + yaml_(a.imageAlt || a.title),
    'author: ' + yaml_(CONFIG.author),
    'pubDate: ' + yaml_(a.pubDate),
    'tags: [' + (Array.isArray(a.tags) ? a.tags.map(yaml_).join(', ') : '') + ']',
    '---'
  ];
  return lines.join('\n');
}

function yaml_(value) {
  return '"' + String(value == null ? '' : value).replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/\n/g,' ') + '"';
}

function extractOutputText_(data) {
  if (data.output_text) return data.output_text;
  const parts = [];
  (data.output || []).forEach(item => {
    (item.content || []).forEach(c => { if (c.text) parts.push(c.text); });
  });
  if (!parts.length) throw new Error('OpenAI returned no text.');
  return parts.join('\n');
}

function githubGet_(path, token) {
  const url = 'https://api.github.com/repos/' + CONFIG.repo + '/contents/' + path + '?ref=' + encodeURIComponent(CONFIG.branch);
  const res = UrlFetchApp.fetch(url, { method:'get', headers:githubHeaders_(token), muteHttpExceptions:true });
  if (res.getResponseCode() === 404) return null;
  if (res.getResponseCode() < 200 || res.getResponseCode() >= 300) throw new Error('GitHub GET error: ' + res.getContentText().slice(0,1000));
  return JSON.parse(res.getContentText());
}

function githubPut_(path, payload, token) {
  const url = 'https://api.github.com/repos/' + CONFIG.repo + '/contents/' + path;
  const res = UrlFetchApp.fetch(url, { method:'put', contentType:'application/json', headers:githubHeaders_(token), payload:JSON.stringify(payload), muteHttpExceptions:true });
  if (res.getResponseCode() < 200 || res.getResponseCode() >= 300) throw new Error('GitHub PUT error: ' + res.getContentText().slice(0,1000));
  return JSON.parse(res.getContentText());
}

function githubHeaders_(token) {
  return {
    Authorization: 'Bearer ' + token,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28'
  };
}

function json_(obj) {
  return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);
}
