const OPENAI_MODEL='gpt-5.6-luna';
const OPENAI_URL='https://api.openai.com/v1/responses';
const WIKIMEDIA_API='https://commons.wikimedia.org/w/api.php';
const DEFAULT_IMAGE='/images/Poganda-Beach-Banggai-IndonesiaJuara-Trip.webp';
const LANGUAGES={id:'Indonesian',en:'English',es:'Spanish',fr:'French',zh:'Chinese'};
const TARGET_LANGUAGES={en:'English',es:'Spanish',fr:'French',zh:'Chinese'};
const MANUAL_TARGET_LANGUAGES={en:'English',es:'Spanish',zh:'Chinese',fr:'French'};
const MAX_RETRIES=4;
const BATCH_SIZE=2;

function doGet(){return jsonResponse({ok:true,service:'Banggai Wonderland CMS',version:'8.0-manual-multilang',status:'online',timestamp:new Date().toISOString()});}
function doPost(e){try{
  if(!e||!e.postData||!e.postData.contents)throw new Error('Request data tidak ditemukan.');
  const data=JSON.parse(e.postData.contents);checkAccessKey(data.accessKey);
  if(data.action==='searchImage')return jsonResponse({ok:true,image:findRelevantImage(String(data.topic||''))});
  if(data.action==='uploadImage')return jsonResponse({ok:true,image:uploadImage(data)});
  if(data.action==='translateManual')return jsonResponse({ok:true,article:translateSingleArticle(data)});
  if(data.action==='publishManual'){const files=publishManualArticles(data.articles);return jsonResponse({ok:true,message:'5 versi artikel manual berhasil dipublish ke GitHub.',files:files});}
  if(data.action==='translate')return jsonResponse({ok:true,articles:translateArticle(data)});
  if(data.action==='publish'){if(!data.articles||typeof data.articles!=='object')throw new Error('Data artikel tidak ditemukan.');const result=publishArticles(data.articles);return jsonResponse({ok:true,message:'5 versi artikel berhasil dipublish ke GitHub.',files:result.files});}
  throw new Error('Action tidak dikenal.');
}catch(error){return jsonResponse({ok:false,error:error&&error.message?error.message:String(error)});}}

function checkAccessKey(value){const expected=PropertiesService.getScriptProperties().getProperty('CMS_ACCESS_KEY');if(!expected)throw new Error('CMS_ACCESS_KEY belum diset di Script Properties.');if(!value||value!==expected)throw new Error('Access key tidak valid.');}
function getOpenAIConfig(){const key=PropertiesService.getScriptProperties().getProperty('OPENAI_API_KEY');if(!key)throw new Error('OPENAI_API_KEY belum diset di Script Properties.');return{key:key,model:OPENAI_MODEL,url:OPENAI_URL};}

function uploadImage(data){let blob,originalName='blog-image.jpg',source='';if(data.dataUrl){const m=String(data.dataUrl).match(/^data:([^;]+);base64,(.+)$/s);if(!m)throw new Error('Format upload foto tidak valid.');const mime=m[1].toLowerCase();if(['image/jpeg','image/png','image/webp','image/gif','image/svg+xml'].indexOf(mime)<0)throw new Error('Format foto harus JPG, PNG, WEBP, GIF atau SVG.');const bytes=Utilities.base64Decode(m[2]);if(bytes.length>8*1024*1024)throw new Error('Ukuran foto maksimal 8 MB.');originalName=String(data.fileName||originalName);blob=Utilities.newBlob(bytes,mime,originalName);}else if(data.imageUrl){source=String(data.imageUrl).trim();if(!/^https?:\/\//i.test(source))throw new Error('Link foto harus dimulai dengan http:// atau https://.');const r=UrlFetchApp.fetch(source,{method:'get',followRedirects:true,muteHttpExceptions:true});if(r.getResponseCode()<200||r.getResponseCode()>=300)throw new Error('Tidak dapat mengambil foto dari link ('+r.getResponseCode()+').');blob=r.getBlob();if(blob.getBytes().length>8*1024*1024)throw new Error('Foto dari link berukuran lebih dari 8 MB.');if(String(blob.getContentType()||'').toLowerCase().indexOf('image/')!==0)throw new Error('Link tersebut tidak mengarah ke file gambar.');originalName=String(blob.getName()||originalName);}else throw new Error('Pilih foto atau masukkan link foto.');const mime=String(blob.getContentType()||'image/jpeg').toLowerCase(),ext=extensionForMime(mime,originalName),base=createSlug(originalName.replace(/\.[^.]+$/,''))||'blog-image',fileName=base+'-'+Utilities.formatDate(new Date(),Session.getScriptTimeZone()||'Asia/Makassar','yyyyMMddHHmmss')+'.'+ext,path='public/images/blog/'+fileName;githubCreateBinaryFile(path,blob.getBytes(),'CMS: Add blog image '+fileName);return{url:'/images/blog/'+fileName,source:source,name:fileName,path:path};}
function extensionForMime(mime,name){if(mime==='image/jpeg')return'jpg';if(mime==='image/png')return'png';if(mime==='image/webp')return'webp';if(mime==='image/gif')return'gif';if(mime==='image/svg+xml')return'svg';const m=String(name||'').toLowerCase().match(/\.(jpg|jpeg|png|webp|gif|svg)$/);return m?(m[1]==='jpeg'?'jpg':m[1]):'jpg';}

function translateArticle(data){const title=String(data.title||'').trim(),description=String(data.description||'').trim(),content=String(data.content||'').trim();if(!title)throw new Error('Judul artikel wajib diisi.');if(!content)throw new Error('Isi artikel wajib diisi.');if(content.length<300)throw new Error('Isi artikel terlalu pendek. Pastikan artikel lengkap sudah ditempel.');const image=data.image&&data.image.url?data.image:{url:DEFAULT_IMAGE,source:'',alt:'Banggai destination in Indonesia'},pubDate=normalizeDate(data.pubDate||getToday()),cfg=getOpenAIConfig();const articles={id:{title:title,description:description||createPreview(content),seoTitle:String(data.seoTitle||title),seoDescription:String(data.seoDescription||description||createPreview(content)),image:image.url||DEFAULT_IMAGE,imageAlt:String(data.imageAlt||image.alt||''),imageSource:String(image.source||''),author:String(data.author||'Banggai Wonderland'),pubDate:pubDate,tags:normalizeTags(data.tags),content:content,preview:createPreview(content)}};const langs=Object.keys(TARGET_LANGUAGES);for(let start=0;start<langs.length;start+=BATCH_SIZE){const batch=langs.slice(start,start+BATCH_SIZE),requests=batch.map(lang=>translatorRequest(cfg,articles.id,TARGET_LANGUAGES[lang])),responses=UrlFetchApp.fetchAll(requests);responses.forEach(function(response,index){const lang=batch[index],status=response.getResponseCode(),raw=response.getContentText();let dataOut;if(isTransientStatus(status)){dataOut=aiRequestResilient(cfg,buildTranslationPayload(cfg,articles.id,TARGET_LANGUAGES[lang]),'Translate ['+lang+']').data;}else{if(status<200||status>=300)throw new Error('OpenAI error ['+lang+'] ('+status+'): '+raw);try{dataOut=JSON.parse(raw);}catch(e){throw new Error('Respons AI tidak valid untuk '+lang+'.');}}const translated=parseTranslationResponse(dataOut,lang);articles[lang]={title:translated.title||articles.id.title,description:translated.description||articles.id.description,seoTitle:translated.seoTitle||translated.title||articles.id.title,seoDescription:translated.seoDescription||translated.description||articles.id.seoDescription,image:articles.id.image,imageAlt:translated.imageAlt||articles.id.imageAlt,imageSource:articles.id.imageSource,author:'Banggai Wonderland',pubDate:articles.id.pubDate,tags:translated.tags.length?translated.tags:articles.id.tags,content:translated.content,preview:createPreview(translated.content)};});if(start+batch.length<langs.length)Utilities.sleep(300);}return articles;}

function translateSingleArticle(data){const lang=String(data.language||'').trim().toLowerCase();if(!MANUAL_TARGET_LANGUAGES[lang])throw new Error('Bahasa manual tidak didukung. Gunakan en, es, zh, atau fr.');const title=String(data.title||'').trim(),description=String(data.description||'').trim(),content=String(data.content||'').trim();if(!title)throw new Error('Judul artikel sumber wajib diisi.');if(!content)throw new Error('Isi artikel sumber wajib diisi.');if(content.length<300)throw new Error('Isi artikel terlalu pendek. Minimal 300 karakter.');const image=data.image&&data.image.url?data.image:{url:DEFAULT_IMAGE,source:'',alt:'Banggai destination in Indonesia'};const source={title:title,description:description||createPreview(content),seoTitle:String(data.seoTitle||title),seoDescription:String(data.seoDescription||description||createPreview(content)),imageAlt:String(data.imageAlt||image.alt||''),tags:normalizeTags(data.tags),content:content};const cfg=getOpenAIConfig();const translated=parseTranslationResponse(aiRequestResilient(cfg,buildTranslationPayload(cfg,source,MANUAL_TARGET_LANGUAGES[lang]),'Translate manual ['+lang+']').data,lang);return{title:translated.title||title,description:translated.description||source.description,seoTitle:translated.seoTitle||translated.title||title,seoDescription:translated.seoDescription||translated.description||source.seoDescription,image:image.url||DEFAULT_IMAGE,imageAlt:translated.imageAlt||source.imageAlt,imageSource:String(image.source||''),author:'Banggai Wonderland',pubDate:normalizeDate(data.pubDate||getToday()),tags:translated.tags.length?translated.tags:source.tags,content:translated.content,preview:createPreview(translated.content),language:lang};}
function publishManualArticles(articles){if(!articles||typeof articles!=='object')throw new Error('Data artikel manual tidak ditemukan.');const required=['id','en','es','zh','fr'],first=articles.id;if(!first||!first.title||!first.content)throw new Error('Artikel Bahasa Indonesia tidak ditemukan.');const translationKey=getToday()+'-'+createSlug(first.title).substring(0,70),files=[];required.forEach(function(lang){const article=articles[lang];if(!article||!article.title||!article.content)throw new Error('Artikel bahasa '+lang+' belum lengkap.');const slug=createSlug(article.title);if(!slug)throw new Error('Slug kosong untuk '+lang+'.');const path='src/content/blog/'+lang+'/'+article.pubDate+'-'+slug+'.md';githubCreateFile(path,createMarkdown(article,translationKey),'CMS: Add manual blog article ['+lang+'] '+article.title);files.push({language:lang,path:path,title:article.title});});return files;}

function normalizeTags(tags){if(Array.isArray(tags)&&tags.length)return tags.map(String).filter(v=>v.trim()).slice(0,12);if(typeof tags==='string'&&tags.trim())return tags.split(',').map(v=>v.trim()).filter(Boolean).slice(0,12);return['Banggai','Indonesia','Travel'];}
function translatorRequest(cfg,source,targetLanguage){return{url:cfg.url,method:'post',contentType:'application/json',headers:{Authorization:'Bearer '+cfg.key},payload:JSON.stringify(buildTranslationPayload(cfg,source,targetLanguage)),muteHttpExceptions:true};}
function buildTranslationPayload(cfg,source,targetLanguage){return{model:cfg.model,input:[{role:'user',content:[{type:'input_text',text:buildTranslationPrompt(source,targetLanguage)}]}],text:{format:{type:'json_object'}},store:false};}
function buildTranslationPrompt(source,targetLanguage){return `You are the professional translator for Banggai Wonderland, a premium travel agency in Banggai, Indonesia.\n\nTASK:\nTranslate the supplied Indonesian travel article into ${targetLanguage}.\n\nSTRICT RULES:\n- You are ONLY a translator. Do not rewrite, expand, shorten, fact-check, research, or creatively reinterpret the article.\n- Preserve every factual claim, meaning, paragraph structure, Markdown heading structure, bullet list, numbered list, table, bold/italic emphasis, link URL, image Markdown, YouTube URL, and important formatting.\n- Never translate, modify, shorten, or remove any URL. URLs must remain byte-for-byte identical.\n- Do not add facts, places, prices, distances, schedules, names, statistics, recommendations, citations, or explanations not present in the source.\n- Do not remove useful information.\n- Keep Banggai place names and proper nouns unchanged unless a standard local-language form is clearly appropriate.\n- Translate titles, descriptions, SEO metadata, tags, headings, and body naturally for the target language.\n- Maintain a premium, natural travel-editorial tone.\n- Preserve Markdown and never return HTML.\n\nSOURCE ARTICLE:\nTITLE:\n${source.title}\n\nDESCRIPTION:\n${source.description}\n\nSEO TITLE:\n${source.seoTitle}\n\nSEO DESCRIPTION:\n${source.seoDescription}\n\nIMAGE ALT:\n${source.imageAlt}\n\nTAGS:\n${source.tags.join(' | ')}\n\nCONTENT:\n${source.content}\n\nRETURN ONLY VALID JSON IN THIS EXACT SHAPE:\n{"title":"...","description":"...","seoTitle":"...","seoDescription":"...","imageAlt":"...","tags":["..."],"content":"..."}`;}
function parseTranslationResponse(response,lang){const output=extractAIText(response);if(!output)throw new Error('AI tidak mengembalikan hasil terjemahan untuk '+lang+'.');let parsed;try{parsed=JSON.parse(cleanJsonOutput(output));}catch(e){throw new Error('Hasil terjemahan bukan JSON valid untuk '+lang+'.');}if(!parsed.content||String(parsed.content).trim().length<100)throw new Error('Isi terjemahan '+lang+' tidak lengkap.');return{title:String(parsed.title||''),description:String(parsed.description||''),seoTitle:String(parsed.seoTitle||''),seoDescription:String(parsed.seoDescription||''),imageAlt:String(parsed.imageAlt||''),tags:normalizeTags(parsed.tags),content:String(parsed.content).trim()};}
function aiRequestResilient(cfg,payload,label){let lastRaw='',lastStatus=0;for(let attempt=1;attempt<=MAX_RETRIES;attempt++){const r=rawAiFetch(cfg,payload);if(r.status>=200&&r.status<300){let data;try{data=JSON.parse(r.raw);}catch(e){throw new Error(label+': Respons OpenAI tidak valid.');}return{data:data,status:r.status};}lastRaw=r.raw;lastStatus=r.status;if(!isTransientStatus(r.status)||attempt===MAX_RETRIES)break;Utilities.sleep(Math.min(30000,Math.pow(2,attempt-1)*1200+Math.floor(Math.random()*800)));}throw new Error(label+' error ('+lastStatus+'): '+lastRaw);}
function rawAiFetch(cfg,payload){const r=UrlFetchApp.fetch(cfg.url,{method:'post',contentType:'application/json',headers:{Authorization:'Bearer '+cfg.key},payload:JSON.stringify(payload),muteHttpExceptions:true});return{status:r.getResponseCode(),raw:r.getContentText()};}
function isTransientStatus(status){return[408,429,500,502,503,504].indexOf(Number(status))!==-1;}

function findRelevantImage(topic){const text=String(topic||'').trim(),lower=text.toLowerCase(),queries=[];if(lower.indexOf('mbuang')!==-1){queries.push('Mbuang-Mbuang Banggai Laut');queries.push('Mbuang Mbuang Banggai');}if(lower.indexOf('paisupok')!==-1)queries.push('Paisupok Lake Banggai');if(lower.indexOf('poganda')!==-1)queries.push('Poganda Beach Banggai');if(lower.indexOf('pulo dua')!==-1)queries.push('Pulo Dua Banggai');if(lower.indexOf('kamumu')!==-1)queries.push('Kamumu Waterfall Banggai');if(lower.indexOf('piala')!==-1)queries.push('Piala Waterfall Luwuk Banggai');queries.push(text+' Banggai Indonesia');for(let i=0;i<queries.length;i++){const r=searchWikimediaImages(queries[i]);if(r)return r;}return{url:DEFAULT_IMAGE,alt:'Banggai tropical destination in Indonesia',source:''};}
function searchWikimediaImages(query){const params=['action=query','format=json','generator=search','gsrnamespace=6','gsrlimit=10','gsrsearch='+encodeURIComponent(query),'prop=imageinfo','iiprop=url|mime|size|extmetadata','iiurlwidth=1600','origin=*'].join('&');let r;try{r=UrlFetchApp.fetch(WIKIMEDIA_API+'?'+params,{method:'get',muteHttpExceptions:true,headers:{'User-Agent':'BanggaiWonderlandCMS/8.0'}});}catch(e){return null;}if(r.getResponseCode()<200||r.getResponseCode()>=300)return null;let data;try{data=JSON.parse(r.getContentText());}catch(e){return null;}const pages=data.query&&data.query.pages?Object.keys(data.query.pages).map(k=>data.query.pages[k]):[],normalized=normalizeSearchText(query),words=normalized.split(' ').filter(w=>w.length>=4),best={value:null,score:-1};pages.forEach(function(page){const info=page.imageinfo&&page.imageinfo[0];if(!info||!info.url)return;const mime=String(info.mime||'').toLowerCase();if(mime==='image/svg+xml'||mime.indexOf('image/')!==0)return;const title=normalizeSearchText(page.title||'');let score=0;words.forEach(w=>{if(title.indexOf(w)!==-1)score+=5;});if(title.indexOf('banggai')!==-1)score+=5;if(info.width&&info.height&&Number(info.width)*Number(info.height)>=1000000)score+=3;if(score>best.score){const meta=info.extmetadata||{};best.score=score;best.value={url:info.thumburl||info.url,alt:meta.ImageDescription&&meta.ImageDescription.value?stripHtml(meta.ImageDescription.value):String(page.title||'Banggai destination'),source:info.descriptionurl||''};}});return best.value;}
function normalizeSearchText(v){return String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();}
function stripHtml(v){return String(v||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();}
function extractAIText(response){if(response&&response.output_text)return response.output_text;if(response&&Array.isArray(response.output))for(let i=0;i<response.output.length;i++){const item=response.output[i];if(!item.content)continue;for(let j=0;j<item.content.length;j++)if(item.content[j].type==='output_text'&&item.content[j].text)return item.content[j].text;}if(response&&Array.isArray(response.candidates)&&response.candidates[0]){const parts=response.candidates[0].content&&response.candidates[0].content.parts||[];for(let i=0;i<parts.length;i++)if(parts[i].text)return parts[i].text;}if(response&&response.choices&&response.choices[0]&&response.choices[0].message&&response.choices[0].message.content)return response.choices[0].message.content;return'';}
function cleanJsonOutput(v){return String(v||'').replace(/^\s*```json\s*/i,'').replace(/^\s*```\s*/i,'').replace(/\s*```\s*$/i,'').trim();}
function createPreview(content){return String(content||'').replace(/^#{1,6}\s+/gm,'').replace(/!\[([^\]]*)\]\([^\)]+\)/g,'$1').replace(/\[([^\]]+)\]\([^\)]+\)/g,'$1').replace(/\s+/g,' ').trim().substring(0,420);}
function createSlug(text){return String(text).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').substring(0,100);}
function normalizeDate(v){const t=String(v||'').trim();return/^\d{4}-\d{2}-\d{2}$/.test(t)?t:getToday();}
function getToday(){return Utilities.formatDate(new Date(),Session.getScriptTimeZone()||'Asia/Makassar','yyyy-MM-dd');}
function yamlEscape(v){return String(v).replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/\r?\n/g,' ');}
function createMarkdown(article,translationKey){let m='---\n';m+='title: "'+yamlEscape(article.title)+'"\n';m+='description: "'+yamlEscape(article.description)+'"\n';if(article.seoTitle)m+='seoTitle: "'+yamlEscape(article.seoTitle)+'"\n';if(article.seoDescription)m+='seoDescription: "'+yamlEscape(article.seoDescription)+'"\n';m+='image: "'+yamlEscape(article.image||DEFAULT_IMAGE)+'"\n';if(article.imageAlt)m+='imageAlt: "'+yamlEscape(article.imageAlt)+'"\n';if(article.imageSource)m+='imageSource: "'+yamlEscape(article.imageSource)+'"\n';m+='author: "'+yamlEscape(article.author||'Banggai Wonderland')+'"\n';m+='pubDate: '+normalizeDate(article.pubDate)+'\n';m+='translationKey: "'+yamlEscape(translationKey)+'"\n';if(Array.isArray(article.tags)&&article.tags.length){m+='tags:\n';article.tags.forEach(tag=>{m+='  - "'+yamlEscape(tag)+'"\n';});}return m+'---\n\n'+String(article.content).trim()+'\n';}
function publishArticles(articles){const files=[],first=articles.id;if(!first||!first.title||!first.content)throw new Error('Artikel Bahasa Indonesia tidak ditemukan.');const translationKey=getToday()+'-'+createSlug(first.title).substring(0,70);Object.keys(LANGUAGES).forEach(function(lang){const article=articles[lang];if(!article||!article.title||!article.content)throw new Error('Artikel bahasa '+lang+' tidak lengkap.');const slug=createSlug(article.title);if(!slug)throw new Error('Slug kosong untuk '+lang+'.');const path='src/content/blog/'+lang+'/'+article.pubDate+'-'+slug+'.md';githubCreateFile(path,createMarkdown(article,translationKey),'CMS: Add translated manual blog article ['+lang+'] '+article.title);files.push({language:lang,path:path,title:article.title});});return{files:files};}
function githubCreateFile(path,content,message){const p=PropertiesService.getScriptProperties(),token=p.getProperty('GITHUB_TOKEN'),owner=p.getProperty('GITHUB_OWNER'),repo=p.getProperty('GITHUB_REPO'),branch=p.getProperty('GITHUB_BRANCH')||'main';if(!token||!owner||!repo)throw new Error('GitHub Script Properties belum lengkap.');const url='https://api.github.com/repos/'+owner+'/'+repo+'/contents/'+path,payload={message:message,content:Utilities.base64Encode(Utilities.newBlob(content).getBytes()),branch:branch},r=UrlFetchApp.fetch(url,{method:'put',contentType:'application/json',headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'},payload:JSON.stringify(payload),muteHttpExceptions:true});if(r.getResponseCode()<200||r.getResponseCode()>=300)throw new Error('GitHub error ('+r.getResponseCode()+'): '+r.getContentText());return JSON.parse(r.getContentText());}
function githubCreateBinaryFile(path,bytes,message){const p=PropertiesService.getScriptProperties(),token=p.getProperty('GITHUB_TOKEN'),owner=p.getProperty('GITHUB_OWNER'),repo=p.getProperty('GITHUB_REPO'),branch=p.getProperty('GITHUB_BRANCH')||'main';if(!token||!owner||!repo)throw new Error('GitHub Script Properties belum lengkap.');const url='https://api.github.com/repos/'+owner+'/'+repo+'/contents/'+path,payload={message:message,content:Utilities.base64Encode(bytes),branch:branch},r=UrlFetchApp.fetch(url,{method:'put',contentType:'application/json',headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'},payload:JSON.stringify(payload),muteHttpExceptions:true});if(r.getResponseCode()<200||r.getResponseCode()>=300)throw new Error('GitHub image error ('+r.getResponseCode()+'): '+r.getContentText());return JSON.parse(r.getContentText());}
function jsonResponse(data){return ContentService.createTextOutput(JSON.stringify(data)).setMimeType(ContentService.MimeType.JSON);}
